name: version test

on:
  push:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    #outputs:
    #  version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout Primary repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: get version
        run: | 
          git describe --tags --abbrev=0

